### ISSUE TITLE
In cmakelists.txt, also wxroute failure

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#175]
These statements

```
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpninclude/wxcurl)
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpninclude/wxcurl/include)
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpnsrc/lz4)
include_directories(BEFORE ${PROJECT_SOURCE_DIR}/ocpnsrc/bitmaps)

```

I don't find them in ocpninclude  or ocpnsrc
so it appears that they are simply not needed is that correct?

**Comment by rgleason** [comment]
`include_directories(BEFORE ${PROJECT_SOURCE_DIR}/libs/wx/include)`

Also I don't seem to find any files here either.

I am having trouble geting weather_routing to build.
I fails even after just applying the circleci/config.yml,  and the ci changes.
Then after I apply the cmake changes it still fails without having made any changes to cmakelists.txt.

Do you have any idea where I should look?  Because it builds and installs but when I enable it, Opencpn crashes.

**Comment by rgleason** [comment]
This problem may be due to your change from CMAKE_SOURCE_DIR   to PROJECT_SOURCE_DIR

I will be watching for it in other PI!!!

**Comment by rgleason** [comment]
It is still failing, now as soon as I try to install it, not just enable it.

In cmakelists.txt

```
if(QT_ANDROID)
    include_directories(BEFORE ${qt_android_include})
    include_directories( ${CMAKE_SOURCE_DIR}/extinclude/GLES2)

    #    #include_directories(BEFORE ${PROJECT_SOURCE_DIR}/libs/glshim/include/GLES)
endif(QT_ANDROID)
```

Should it be  PROJECT_SOURCE_DIR?

**Comment by rgleason** [comment]
I haven't been able to get this to build properly,
the changes don't seem that drastic, 
but I think you changed to gles from libtess2 and that may be part of the problem?

I pushed the failing commiit to here so you could take a look  weather_routing  update-tp  branch.
https://github.com/rgleason/weather_routing_pi/tree/update-tp

**Comment by jongough** [comment]
At line 114 in weather_routing_pi.cpp the setting of m_pWeather_Routing to NULL is commented out, don't know why. So I set it to null in the constructor by adding this at the end (new line 96). I rebuilt the plugin and it all works, the bits I tested. The issue was that without setting the value to null it could contain anything and that was used in tests. This resulted in OCPN using an invalid value and crashing.

**Comment by rgleason** [comment]
Yes, this fixed it.    I left it at line 113 and took the comments out (don't know why I commented out) but have moved this line  up to a new LINE 96  within the  "constructor"   and have tested and it does work!!
 
```
      m_parent_window = GetOCPNCanvasWindow();

      **m_pWeather_Routing = NULL;**   <--- MOVED up to LINE 96

#ifdef PLUGIN_USE_SVG
```

If I am missing one of these for Polar_pi which fails Opencpn every time I disable it, should I try that?
Thank you.

**Comment by jongough** [comment]
I think with polar_pi the creation of the dialog may be done after OCPN tries to set the colorscheme. So either it needs to be checked for being valid before this call or it needs to be created earlier, either in the instantiation or the Init parts. Currently the only place the PolarDialog is created is in ShowPreferencesDialog (line 220 in polar_pi.cpp).

**Comment by rgleason** [comment]
Humm, there are some other problems too.
1.. In preferences there is a checkbox  "Show Polar Icon"  which makes no sense to me because there would be no way to activate the plugin.
2.  This checkbox is connected to       if(m_bPolarShowIcon)  in  polar_pi.cpp  Lines 119, 212, 252, 265-269, 420, 469.
3. Since there are so many instances, the function must work in some way that is not working now, or is outdated.
4. When the plugin is disabled O crashes.
5. I still have been unable to get the svg icons showing. I've been through it a dozen times and don't see why, however the puzzle icon works as would be expected and shows "Polar" in the popup.
6. I am going to push Polar_pi up to   Polar_pi   master-update  branch in case you can advise.
7. https://github.com/rgleason/polar_pi/tree/master-update

I don't know if I should try to remove the Show Polar Icon from preferences and just leave the parameter but set it to true, or clean up this mess, or perhaps try to get it working when Show Icon is unchecked somehow.

**Comment by jongough** [comment]
I try to keep clear of other plugins unless it is related to frontend2. As I use frontend2 for three of my plugins I try to make sure it works OK. If other plugins fail it is probably not due to frontend2, but changes in OCPN, changes in the underlaying environment, or usage patterns. This should be fixed by the plugin developer, not you. In the case where OCPN crashes when a plugin is disabled it would suggest that there are plugin issues and not build issues. OCPN is changing, often without notice, and normally with very little documentation/information about why it changed and what has to be done to support the 'new' way of working.
