### ISSUE TITLE
PI disable causes O to fail

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#181]
Plugin Disable Checkbox causes OpenCPN to fail

ochart   - OK
statusbar - Fixed
polar  - next  [branch master-update](https://github.com/rgleason/polar_pi/tree/master-update)
logbookkonni - Fixed
vfkaps  -  Mike knows about this
shipdriver   -  Mike knows about this
otcurrent   -  Mike knows about this
aisradar  - Fixed

Also have an Issue under Opencpn here
https://github.com/OpenCPN/OpenCPN/issues/2418

**Comment by jongough** [comment]
The problem is in the plugin. I have just tried both statusbar and logbookkonni and after install and activate I get the crash if I stop and start OCPN then deactivate statusbar. The crash occurs in chart1.cpp at line 6016 trying to show the options modal dialog, I think. 

I have noticed that there is another problem with statusbar, if I open the preferences from OCPN/Settings/statusbar, I cannot access the settings dialog until I close the OCPN Settings dialog. This suggests that there is a coding error in statusbar. This is not, as far as I can tell, a frontend2 issue. It may be a statusbar issue or and OCPN issue.

I did the test on Linux Mint 20.2 which has Ubuntu 20.10 underlying it. I had to select 'ubuntu-gtk3-x86_64:20.04' as the compatability flavour to load the plugins from the master catalog.
