### ISSUE TITLE
Plots_pi  flatpak build, make wxJSON work with Linux

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#189]
Jon, for plugins that fail Flatpak, should i be following this?
Should I just change my version of Testplugin use that for this round?
https://github.com/rgleason/plots_pi/commits/master

PS: Everything built!

**Comment by jongough** [comment]
You need to keep using the latest version of testplugin as it is being changed to keep up to date with the build requirements. It is part of the issue I raised about complexity of plugin manager, but this does not concern some. If a plugin is not being updated continually it should work for some time once you have it converted. If someone is modifying the plugin then they should also update the build environment, i.e. Frontend2, as it is likely that it may not build due to changes in the build process (things are moving on in circleci/appveyor and old builds are being depricated and new environments are being stood up, so circleci.yml does change as well as some other files).

**Comment by rgleason** [comment]
Yes, these are good, and I'll get them into the TP Manual.

**Comment by rgleason** [comment]
Jon, the original point is that  TP does not have

```
         -  https://flathub.org/repo/flathub.flatpakrepo
          +  https://dl.flathub.org/repo/flathub.flatpakrepo
```

Since I have all these failing flatpaks and this one works I am going to use this, and will probably change my version of TP accordingly..

**Comment by jongough** [comment]
I have put up a new version number, 1.0.176.1, to make it easer to get the correct version. It is currently going though the build process.

**Comment by jongough** [comment]
It's only a version number change in CMakeLists.txt as the change to the script file had already been made. Unfortunately you picked up testplugin between two pushes and without a version number change you don't know that things have changed.
