### ISSUE TITLE
What happened to the If not Flatpak logic?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#213]
I need a place to put  the includes for nmea, etc?
I though flatpak did not use those.

**Comment by jongough** [comment]
I do not know what you are referring too. Which file did you think the 'missing' logic was in? The only ones I have inside the OD CMakeLists.txt file is for gdal and tinyxml as they do not work in FLATPAK. For testplugin it stops the inclusion of tinyxml. nmea is OK in flatpak.

**Comment by rgleason** [comment]
For testplugin it stops the inclusion of tinyxml. nmea is OK in flatpak.

Ok. I am not privy to these changes.

**Comment by jongough** [comment]
These are settings that have been there since flatpak was included in the build process. It just happens that they are there in the plugin customisable section as the plugin maintainer knows what is needed (or will find out during testing) what will and wont work. That is what I had to do with OD. Frontend2 cannot determine this on another plugins behalf so it is not in the 'standard' supplied parts of the build process.

**Comment by rgleason** [comment]
Yes. Sometimes I don't know what has happened and what we are supposed to do.
