### ISSUE TITLE
AutoTrackRaymarine Correct versions of opencpn.lib and ocpn-plugin.h?

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#227]
Please see Dave's response here, I could not build autotrackraymarine_pi with the current testplugin files.

https://github.com/OpenCPN/plugins/issues/511#issuecomment-988787559

Also note that Dave added back into [ci/control  ](https://github.com/rgleason/climatology_pi/blob/master/ci/control) the file   libgtk2.0-dev,   for building bionic   

I think that we should probably be using these changes for testplugin. I realize that it is inevitable that I will have to rebuild 20 plugins again, but I would like to be as current as possible.

**Comment by rgleason** [comment]
Also see the climatology change to plugininstall.cmake

**Comment by bdbcat** [comment]
If it fails with most current opencpn.lib, please post a link to failing buildlog.

**Comment by rgleason** [comment]
I've built climatology with the same files as AutoTrackRaymarine  (api117) and climatology works fine.
In fact with your changes it seems to load data much better.

**Comment by jongough** [comment]
Testplugin does not supply ocpn-plugin.h or the associated opencpn.lib file. Yes it uses them, the same as every plugin, but every plugin needs to have and maintain their own version depending on what they are trying to do. Frontend2 does try to keep the opencpn.lib file current by downloading from sourceforge, but that file, unfortunately, does not seem to be being updated.

I have raised before the issue with building automatically in the cloud and having to rely on someone to keep the needed files up to date. This happens for android as will with the 'master.zip' file and you have now fallen foul of the ocpn-plugins.h/opencpn.lib files not being maintained.

The only change I see in the MacOS script is the adding of the '-' before the 'eq' for 315 wxversion. This change is in v1.0.184.3 .

**Comment by rgleason** [comment]
Jon why isn't testplugin keep abreast of the current version of Opencpn. You are using API 116 files when Opencpn 5.6.0 is API 117!!!   This seems very retrograde to me.

**Comment by jongough** [comment]
Plugins determine the best version of the API to use. There is no advantage in chasing newer versions if the new functionality is not going to be used. Testplugin uses the version it needs to. The plugin developer is responsible for deciding on the API version to use not Frontend2. Frontend2 is API agnostic.

I note that someone has updated the opencpn.lib file on sourceforge so I have changed Frontend2 to use that version in the appveyor.yml (Frontend2 v 1.0.185.0). That should the be version that matches API 1.17, I am hoping that when newer versions of the API come out that this file is updated accordingly. Assuming there is no break to backwards compatability this should be OK, i.e using opencpn.lib for API 1.17 with ocpn-plugin.h for API 1.16, but this has been broken in the recent past.

When changes are made to Frontend2 supplied build files, i.e. PluginInstall.cmake, it would be very useful if a pull request was made against testplugin_pi so that I can incorporate this in the latest version. I don't have time to follow all the discussions going on or the changes being made, so github is really useful for changes/contributions to be made by others. Frontend21.0.185.0 now includes the change for UserIcons for MacOS.

**Comment by bdbcat** [comment]
_Assuming there is no break to backwards compatability this should be OK, i.e using opencpn.lib for API 1.17 with ocpn-plugin.h for API 1.16_

Exactly right.  The contract for Released APIs is:
Plugin API revisions are _ALWAYS_ additive only.  So if you do not need API117 functions, than API116 is fine, both the include and lib file.  There is no need to chase the API.  Having said that, there is also no harm in using the most modern include and lib files, for reason stated.

**Comment by rgleason** [comment]
Jon, I just noticed the change in Pluginstall on the fly and I will have to make a new PR in Testplugin for it, so someone has to do this work anyway. I will try to do it.

**Comment by jongough** [comment]
I have done the update for MacOS UserIcons, so unless there is another change it should all be OK now.

**Comment by rgleason** [comment]
Thanks very much Jon, that was a quick change. I am using testplugin now 1.0.185.0   to update PI's 
I have discovered that using an updated ocpn-plugin.h  (api117) with an api 116 plugin results in issues.
So I guess it is true that you must have an ocpn-plugin.h that matches the plugins intended API.

**Comment by jongough** [comment]
The issue with using a newer ocpn_plugin.h should not cause an issue as it should be backwards compatible. Just make sure you don't change the base on which the plugin is based (i.e. if it was 116 leave it at 116 don't change to 117). If it is causing issues you should raise an issue against OCPN so that it can be looked at and fixed.

**Comment by rgleason** [comment]
Well, there were issues. I will have to go back an recreate it. I think it was with weather_routing which is the plugin that I started with. I was using the most current and update version of ocpn-plugin.h and got all kinds of errors.

**Comment by jongough** [comment]
I think the move to API 1.16 caused and issue with the movement of the plugin data directory and the reuse and modification of a particular call which was an API 1.13 member.

**Comment by rgleason** [comment]
That sounds pretty specific. I don't understand how this really works, but I can see that it is complex and important.

**Comment by rgleason** [comment]
I think this is outdated. Closing
