### ISSUE TITLE
Merging your recent changes

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#271]
That was a PITA because there were conflicts, due to the fact that you did not merge my PR.
So there was a whole lot of git and bash going on.
You didn't increment the version either, but I got it merged while keeping the history specifically bdbcats PR's in the history which is good.

**Comment by rgleason** [comment]
Now weatherfax is not building for build-flatpak-arm64
  https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/320/workflows/de977eb4-3b67-4e8c-bdaf-4176d31b6e7d/jobs/4198

Do you know what the brown messages are all about?  I can't rerun it, that is frozen out. Perhaps it is not finished?

**Comment by rgleason** [comment]
Now build-macos is not starting due to https://status.circleci.com/
and build-flatpak-arm64  failed, but there is brown unfinished lines.

**Comment by rgleason** [comment]
IT appears macos has built. now I just have problems with [build-flatpak-arm64](https://app.circleci.com/pipelines/github/rgleason/weatherfax_pi/320/workflows/de977eb4-3b67-4e8c-bdaf-4176d31b6e7d/jobs/4198)

> flatpak-builder is already the newest version (1.0.10-1).
> flatpak is already the newest version (1.6.5-0ubuntu0.4).
> 0 upgraded, 0 newly installed, 0 to remove and 376 not upgraded.
> W: --force-yes is deprecated, use one of the options starting with --allow instead.
> + flatpak remote-add --user --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
> 
> Note that the directories 
> 
> '/var/lib/flatpak/exports/share'
> '/home/circleci/.local/share/flatpak/exports/share'
> 
> are not in the search path set by the XDG_DATA_DIRS environment variable, so
> applications installed by Flatpak may not appear on your desktop until the
> session is restarted.
> 
> + '[' stable = beta ']'
> + flatpak install --user -y flathub org.freedesktop.Sdk//20.08
> error: Nothing matches org.freedesktop.Sdk in remote flathub
> 
> Exited with code exit status 1

Any ideas? Otherwise I will need to go to bdbcat and he is very busy right now.

**Comment by jongough** [comment]
I created a pull request which only had one failure due to something happening with flatpak and 20.08 not being found. So I merged that into the master stream and now all flatpak builds are failing.
See update:
https://app.circleci.com/pipelines/github/jongough/testplugin_pi/1193/workflows/54e7d848-3d3e-44c3-8abf-31e9e18b82c1
master:
https://app.circleci.com/pipelines/github/jongough/testplugin_pi/1194/workflows/367b2592-3c69-4129-b8f4-e41765892ea1

This appears to be a propagation issue with a new version(?) of flatpak.

I did try to respond to leamas, but the responses were less than helpful. We are now, currently, stuck with no build capability for flatpak. If the flatpak process is going to be this unstable it may have to be ditched.

I was having difficulty merging your changes as I could not get github/git to get to a point where the merge was successful, so I just recreated the changes. I will not create another update to increase the version number so that it is clearer.

**Comment by rgleason** [comment]
Jon, 
I am sorry about this. While you were away, he asked in some Issue, if we were going to support two versions of flatpak  (he did not ask me anything about it).  And I saw that you said you'd prefer to support the newer version.   I can't find the Issue yet.

I decided I would say nothing because it was not addressed to me.

**Comment by rgleason** [comment]
Jon has updated the template. Done
