### ISSUE TITLE
Old src structure -- update to new?

### ISSUE THREAD

**Issue by leamas** [jongough/testplugin_pi#3]
The main opencpn program has reorganized the sources, basically moved libraries in src/ to a separate libs/ dir. It might make sense to do the same also in a template plugin to make a cleaner separation of dependencies from the main sources

**Comment by jongough** [comment]
Done but with slight mods. OCPN stuff is still separate from new libs and orig src.

**Comment by leamas** [comment]
Here, I don't follow you....

First: this is just a proposal. If you are not interested in it, please just state so and close bug. Case closed.

Otherwise: look for example at src/mygdal. In current opencpn this is libs/gdal. Notably differences:

  - The name, gdal, is the proper name. After all, it's a bundled copy of https://gdal.org/
  - It has a separate cmake setup, isolating it from the overall setup.
  - It creates a cmake transitive library which carries target, include flags etc, so that the main program just have to include one thing.
  - Some code which was added (don't remember the details) has been moved out of the lib into src to make it a "clean" library so to speak.
  - Since it's not part of the overall compilation there are no dependencies from  gdal to src, just the other way around.

So: what am I missing?

**Comment by leamas** [comment]
Thinking about it: when doing a template, using the current opencpn setup makes a lot of sense. Different plugins will certainly have to bundle different libs. Using the current scheme, this could be done by copying the library from opencpn to a new libs/ dir, and make a tatget_link_libraries. This is a far better scheme than having library sources, include flags etc in ./CMakeLists.txt

**Comment by jongough** [comment]
This is not a template rather it is my test plugin that lets me try out the ODAPI and JSON messages. I needed this when making changes to cater for squiddio using OD rather than OCPN. Having built it I thought it may be useful to others that want to use the ODAPI/JSON to display objects on the OCPN desktop as it shows how it is done and allows bits of code to be picked up and used in other plugins. Currently Watchdog, Weather Routing and now Squiddio use this. The template plugin is the dashboard_pi which shows how to code up a plugin for OCPN.

I am trying to make it cleaner, but it is a 'hack' plugin that is used by developers only (or should be).

**Comment by leamas** [comment]
Well, in that case I guess this is out of context. Closing
