### ISSUE TITLE
CI: Ubuntu x86_64 22.04 Jammy  (Pypilot_pi) - correct wxWidgets

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#375]
https://github.com/pypilot/pypilot_pi/issues/37#issuecomment-1871679681

> Marco...
> Thanks to your help, we have resolved this trouble. The root cause was that the CI builds were using the incorrect version of wxWidgets. CI was using 3.2.1, but it should have matched the OCPN build using 3.2.2.
> 
> Please update the plugin catalog, load pypilot_pi v0.40.31.2, and confirm/close.
> 
> Thanks again

**Comment by rgleason** [comment]
Jon, take care, updating this there are some new files.

**Comment by jongough** [comment]
I am not sure what the changes are. I can see there is a new config.yml for API 118, but not sure why this is needed. The API has nothing to do with the build process, that is internal to the plugin. 

I have made the minor changes in the other files. However, opencpn-libs is only updated when needed by the plugin, the method to do this and change the branch of opencpn-libs in use is done by the use of two scripts. The opencpn-libs are not transferable to the plugins via their git, this needs to be done on the individual git repository for the build process.

**Comment by rgleason** [comment]
Dave did the changes on pypilot, see the PR and merge in my repos.
https://github.com/rgleason/pypilot_pi/commits/master/
Maybe that will help.

When I do a compare between my repo and yours I see differences between opencpn-libs which I believe should not be the case.

**Comment by jongough** [comment]
I believe all the latest changes are in testplugin 1.0.291.0 . The opencpn-libs are very unlikely to be a the same commit level in each of the plugins. Rather like the API version of OCPN, if you don't need it don't change it. There is a simple script to update the version of opencpn-libs when using it on your pc and you can then commit that change and push up to git, circleci will then build with that. If you are not careful you will be continuously building as opencpn-libs get updated.

**Comment by rgleason** [comment]
Agreed. But isn't it best to keep opencpn-libs updated whenever you build?

**Comment by jongough** [comment]
The version of opencpn-libs in testplugin is irrelevant to plugins using this process. The contents of opencpn-libs has to be 'cloned' into each git otherwise the build will fail. Also, if the opencpn-libs is updated continuously it is highly likely that failures will occur as 'something' changes that will need to be fixed for the plugin. This would have the effect of destabalising the plugin and require significant testing. So, if you are building new capability and need new stuff from opencpn-libs then you would update the submodule (its what update_submodule_branch.sh does). Otherwise just leave it as is.

**Comment by rgleason** [comment]
Closing
