### ISSUE TITLE
CI: Drop support Buster/Bionic builds

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#380]
Drop support for Buster/Bionic builds #379

**Comment by jongough** [comment]
Why, if it still works leave it. Many people, including me, have 'older' equipment that may not support the newer versions. If a plugin cannot be built successfully for an environment then that is OK. But many can so they should not be prevented from doing so. We kept WinXP builds long after it was retired.

It does raise the issue of keeping older versions in the prod environment with XML and plugin manager support. Otherwise OCPN will be following Apple, MS, Android in requiring users to continually update hardware and software at considerable costs. I am not sure why OCPN seems to be going down this path.

**Comment by rgleason** [comment]
I expect we can keep these until 5.10 comes out.

**Comment by rgleason** [comment]
Done
