### ISSUE TITLE
Flatpak fails now

### ISSUE THREAD

**Issue by rgleason** [jongough/testplugin_pi#43]
https://github.com/jongough/testplugin_pi/runs/578687367

**Comment by rgleason** [comment]
This one seems to work https://github.com/jongough/testplugin_pi/runs/579705032
 Try to allow gzip to work on flatpak build
fix_up @jongough
20c4865

**Comment by jongough** [comment]
Its the edge cases that are catching me out. I have another build going with the chmod for files within the docker process but no in the cloudsmith script. Will see how that goes.

**Comment by rgleason** [comment]
Flatpak built.  Just waiting for 2nd Travis raspbian armhf to finish.  Also Added updated and reformatted Frontend2.md.  Closing

**Comment by rgleason** [comment]
Maybe this should be open for testplugin?

**Comment by jongough** [comment]
I think it now works. It is a bit ugly in the cloudsmith.sh.in file as there seems to be an issue with tar and picking up new files properly and then gzip seeming to see old files not the new ones. I have left all the debugging code in there as it lets you see what is going on and they do very little apart from listing the directories and showing contents of tar files which is not much compared to the other 'userful' information used in the output so that you can see what you are doing.

**Comment by jongough** [comment]
testplugin_pi 1.0.67 appears to be working for all builds. I have merged it into the master so it should be easy to pickup.

**Comment by rgleason** [comment]
Thank you! It works.
